name: UK Air Quality Daily Sync

on:
  schedule:
    # This runs every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # This lets us run it manually for testing!

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/checkout@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Pipeline
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_DATASET_ID: ${{ secrets.GCP_DATASET_ID }}
        GCP_TABLE_ID: ${{ secrets.GCP_TABLE_ID }}
      run: |
        # Creating a temporary key file from the secret
        echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
        python fetch_air_quality.py
